<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>

        <Title>CatUI.Data</Title>
        <Description>
            Contains most of the data containers for almost every aspect of CatUI, including brushes, event arguments,
            colors and geometry descriptors. It is closely tied to CatUI and SkiaSharp, so using it in a non-CatUI project
            doesn't have much sense, except for some classes that are simply data containers.
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp" Version="2.88.8" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Platform\CatUI.Platform.Essentials\CatUI.Platform.Essentials.csproj" />
        <ProjectReference Include="..\CatUI.Utils\CatUI.Utils.csproj" />
    </ItemGroup>

</Project>
