<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(TargetFrameworks);net8.0-windows</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(TargetFrameworks);net8.0-macos</TargetFrameworks>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <Version>0.1.0</Version>
        <Title>CatUI.Data</Title>
        <Description>
            Contains most of the data containers for almost every aspect of CatUI, including brushes, event arguments,
            colors and geometry descriptors. It is closely tied to CatUI and SkiaSharp, so using it in a non-CatUI project
            doesn't have much sense, except for some classes that are simply data containers.
        </Description>
        <Copyright>Copyright (c) moldovanedy 2025</Copyright>
        <PackageTags>UI;User Interface;fast</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Authors>Moldovan Eduard</Authors>

        <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp" Version="2.88.8"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Platform\CatUI.Platform.Essentials\CatUI.Platform.Essentials.csproj"/>
        <ProjectReference Include="..\CatUI.Utils\CatUI.Utils.csproj"/>
        <ProjectReference Include="..\Platform\CatUI.Platform.Linux\CatUI.Platform.Linux.csproj"/>
        <ProjectReference Include="..\Platform\CatUI.Platform.Windows\CatUI.Platform.Windows.csproj"/>
    </ItemGroup>

</Project>
