<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <Version>0.1.0</Version>
        <Title>CatUI</Title>
        <Description>A small, fast and easy-to-use UI library for modern .NET cross-platform development.</Description>
        <Copyright>Copyright (c) moldovanedy 2025</Copyright>
        <PackageTags>UI;User Interface;fast</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Authors>Moldovan Eduard</Authors>

        <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CatUI.Elements\CatUI.Elements.csproj" />
        <ProjectReference Include="..\CatUI.Data\CatUI.Data.csproj" />
        <ProjectReference Include="..\CatUI.NativeAssets\CatUI.NativeAssets.csproj" />
        <ProjectReference Include="..\CatUI.RenderingEngine\CatUI.RenderingEngine.csproj" />
        <ProjectReference Include="..\Platform\CatUI.Platform\CatUI.Platform.csproj" />
        <ProjectReference Include="..\Windowing\CatUI.Windowing.DesktopApp\CatUI.Windowing.DesktopApp.csproj" />
    </ItemGroup>

</Project>
