<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>

        <Title>CatUI.Windowing.Common</Title>
        <Description>Contains the logic shared by all types of application windows (surfaces) that CatUI runs on.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../CatUI.Elements/CatUI.Elements.csproj" />
    </ItemGroup>

</Project>
