<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <!--<CatUseAngle>true</CatUseAngle>-->

        <Title>CatUI.Windowing.Desktop</Title>
        <Description>Contains the logic for creating and managing windows on desktop platforms for CatUI.</Description>
    </PropertyGroup>

    <PropertyGroup Condition="'$(CatUseAngle)' == 'true'">
        <DefineConstants>$(DefineConstants);CAT_USE_ANGLE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CatUI.RenderingEngine\CatUI.RenderingEngine.csproj" />
        <ProjectReference Include="..\CatUI.Windowing.Common\CatUI.Windowing.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OpenTK.Graphics" />
        <PackageReference Include="OpenTK.Windowing.GraphicsLibraryFramework" />
    </ItemGroup>

</Project>
