<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <!--<CatUseAngle>true</CatUseAngle>-->

        <Title>CatUI.Windowing.Desktop</Title>
        <Description>Contains the logic for creating and managing windows on desktop platforms for CatUI.</Description>
    </PropertyGroup>

    <PropertyGroup Condition="'$(CatUseAngle)' == 'true'">
        <DefineConstants>$(DefineConstants);CAT_USE_ANGLE</DefineConstants>
    </PropertyGroup>

    <!--    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows')) Or $(RuntimeIdentifier.StartsWith('win'))">-->
    <!--        <DefineConstants>$(DefineConstants);CAT_LOCAL_WINDOWS</DefineConstants>-->
    <!--    </PropertyGroup>-->

    <!--    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX')) Or $(RuntimeIdentifier.StartsWith('osx'))">-->
    <!--        <DefineConstants>$(DefineConstants);CAT_LOCAL_MACOS</DefineConstants>-->
    <!--    </PropertyGroup>-->

    <!--    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux')) Or $([MSBuild]::IsOSPlatform('FreeBSD')) Or $(RuntimeIdentifier.StartsWith('linux')) Or $(RuntimeIdentifier.StartsWith('unix'))">-->
    <!--        <DefineConstants>$(DefineConstants);CAT_LOCAL_LINUX</DefineConstants>-->
    <!--    </PropertyGroup>-->

    <ItemGroup>
        <PackageReference Include="OpenTK.Graphics" Version="4.9.4" />
        <PackageReference Include="OpenTK.Windowing.GraphicsLibraryFramework" Version="4.9.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CatUI.RenderingEngine\CatUI.RenderingEngine.csproj" />
        <ProjectReference Include="..\CatUI.Windowing.Common\CatUI.Windowing.Common.csproj" />
    </ItemGroup>

</Project>
