<Project>
    <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="SkiaSharp" Version="2.88.8" />
        <PackageVersion Include="SkiaSharp.Views" Version="2.88.8" />
        <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="2.88.8" />

        <!-- desktop -->
        <PackageVersion Include="OpenTK.Graphics" Version="4.9.4" />
        <PackageVersion Include="OpenTK.Windowing.GraphicsLibraryFramework" Version="4.9.4" />

        <!-- Linux -->
        <PackageVersion Include="Tmds.DBus.Protocol" Version="0.21.2" />

        <!-- tool -->
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />

        <!-- tests -->
        <PackageVersion Include="coverlet.collector" Version="6.0.2" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageVersion Include="NUnit" Version="4.2.2" />
        <PackageVersion Include="NUnit.Analyzers" Version="4.4.0" />
        <PackageVersion Include="NUnit3TestAdapter" Version="4.6.0" />
    </ItemGroup>
    
</Project>
