<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../src/CatUI/CatUI.csproj" />
        <ProjectReference Include="../../../src/CoreExtensions/CatUI.CoreExtensions.Itania/CatUI.CoreExtensions.Itania.csproj" />
        <ProjectReference Include="../../../src/CoreExtensions/CatUI.CoreExtensions.I18n/CatUI.CoreExtensions.I18n.csproj" />
        <ProjectReference Include="../../../src/CoreExtensions/CatUI.CoreExtensions.I18n.GetText/CatUI.CoreExtensions.I18n.GetText.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets/**" />
    </ItemGroup>
</Project>
