<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <CatUseAngle>true</CatUseAngle>
    </PropertyGroup>

    <Target Name="DefineAngle" BeforeTargets="Build">
        <Message Text="Building with CatUseAngle" />
        <!--<MSBuild Projects="CatTest.csproj" Properties="CatUseAngle=true" />-->
        <PropertyGroup>
            <CatUseAngle>true</CatUseAngle>
        </PropertyGroup>
    </Target>

    <ItemGroup>
        <EmbeddedResource Include="Assets/**/*.*" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\CatUI\CatUI.csproj" />
    </ItemGroup>

</Project>
