<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>

        <Title>CatUI.Elements</Title>
        <Description>
            Contains all the UI elements for CatUI, as well as other utilities for creating beautiful user interfaces.
            It can't be used on non-CatUI projects (or it is useless that way).
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CatUI.Data\CatUI.Data.csproj" />
        <ProjectReference Include="..\CatUI.RenderingEngine\CatUI.RenderingEngine.csproj" />
        <ProjectReference Include="..\Platform\CatUI.Platform\CatUI.Platform.csproj" />
    </ItemGroup>

</Project>
