<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>

        <Title>CatUI.Platform</Title>
        <Description>
            Contains the unified API for accessing different platform-specific APIs, like native alerts, file pickers,
            notifications, and more. This can be used in non-CatUI applications, even the ones built in other UI
            frameworks.
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CatUI.Platform.Essentials\CatUI.Platform.Essentials.csproj" />

        <ProjectReference Condition="$(DefineConstants.Contains('CAT_LOCAL_LINUX'))" Include="..\CatUI.Platform.Linux\CatUI.Platform.Linux.csproj" />
        <ProjectReference Condition="$(DefineConstants.Contains('CAT_LOCAL_WINDOWS'))" Include="..\CatUI.Platform.Windows\CatUI.Platform.Windows.csproj" />
        <ProjectReference Condition="$(DefineConstants.Contains('CAT_LOCAL_WINDOWS')) Or $(DefineConstants.Contains('CAT_LOCAL_MACOS')) Or $(DefineConstants.Contains('CAT_LOCAL_LINUX'))" Include="..\CatUI.Platform.DesktopCommon\CatUI.Platform.DesktopCommon.csproj" />
    </ItemGroup>

</Project>
