<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../CatUI.Platform.CommonInterface/CatUI.Platform.CommonInterface.csproj" />
        <ProjectReference Include="../../CatUI.Data/CatUI.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- 
        we need conditions because net8.0-linux is not defined and we don't want to include this with every platform 
        (it's net8.0, so it would get included otherwise) 
        -->
        <PackageReference Include="OpenTK.Windowing.GraphicsLibraryFramework" />
        <PackageReference Condition="$(DefineConstants.Contains('CAT_LINUX')) Or $(DefineConstants.Contains('CAT_ANY_PLATFORM'))" Include="Tmds.DBus.Protocol" />
    </ItemGroup>

</Project>
