<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CatUI.Platform.Essentials\CatUI.Platform.Essentials.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="OpenTK.Windowing.GraphicsLibraryFramework" Version="4.9.4"/>
        <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.2"/>
    </ItemGroup>

</Project>
