<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CatUI.Platform.Essentials</RootNamespace>

        <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp" Version="2.88.8" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CatUI.Utils\CatUI.Utils.csproj" />
    </ItemGroup>

</Project>
