<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CatUI.Utils\CatUI.Utils.csproj" />
        <ProjectReference Include="..\..\CatUI.Data\CatUI.Data.csproj" />
    </ItemGroup>

</Project>
