<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-android</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp.Views" Version="2.88.8" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CatUI.Windowing.Common\CatUI.Windowing.Common.csproj" />
    </ItemGroup>
</Project>
