<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <Title>CatUI.Utils</Title>
        <Description>
            Contains some basic utilities that are actually independent of CatUI and can be used in any project
            even if it doesn't use CatUI.
        </Description>
    </PropertyGroup>

</Project>
