<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;</TargetFrameworks>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup Condition="!$(DefineConstants.Contains('CAT_LOCAL_MACOS'))">
        <Compile Remove="**/*" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CatUI.Platform.CommonInterface\CatUI.Platform.CommonInterface.csproj" />
    </ItemGroup>
</Project>
