<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CatUI.Platform.CommonInterface\CatUI.Platform.CommonInterface.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OpenTK.Windowing.GraphicsLibraryFramework" />
    </ItemGroup>

</Project>
